randomize();
cagirma_y = random_range(-100,200);
var ust_boru = instance_create_layer(x,cagirma_y,"Instances",obj_ust_boru);
ust_boru.image_angle = 180;
ust_boru.image_xscale *= 4;
ust_boru.image_yscale *= 4;
var alt_boru = instance_create_layer(x-10,ust_boru.y+880,"Instances",obj_alt_boru);
alt_boru.image_xscale *= 4;
alt_boru.image_yscale *= 4;
instance_create_layer(x+60,cagirma_y,"Instances",obj_skor_arttiran);
alarm[0] = 200;
